### ISSUE TITLE
Always NPE while reading mappings

### ISSUE THREAD

**Issue by iceBear67** [FabricMC/lorenz-tiny#6]
Code:
```java
TinyMappingFormat.TINY.read(Path.of("1.18.1.tiny"),"official","intermediary");
```
the mapping: https://raw.githubusercontent.com/FabricMC/intermediary/master/mappings/1.18.1.tiny
![image](https://user-images.githubusercontent.com/48877375/148664615-d2523bc8-493e-4259-b485-50157ba17971.png)
I have no idea about how can this to be a null. I also tried `1.17.1.tiny` but it didn't make a difference

stacktrace:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.lastIndexOf(int)" because "deobfuscatedName" is null
	at org.cadixdev.lorenz.impl.model.InnerClassMappingImpl.setDeobfuscatedName(InnerClassMappingImpl.java:91)
	at org.cadixdev.lorenz.impl.model.InnerClassMappingImpl.setDeobfuscatedName(InnerClassMappingImpl.java:39)
	at net.fabricmc.lorenztiny.TinyMappingsReader.read(TinyMappingsReader.java:76)
	at net.fabricmc.lorenztiny.TinyMappingFormat.read(TinyMappingFormat.java:177)
	at net.fabricmc.lorenztiny.TinyMappingFormat.read(TinyMappingFormat.java:199)
```

**Comment by iceBear67** [comment]
solved by using mappings from yarn
